POST http://localhost:8083/send
Content-Type: application/json

{
  "from": "jhon.smith2@example.com",
  "to": "x@exmaple.com",
  "subject": "Hello World",
  "message": "Hello"
}

### Authenticate
POST http://127.0.0.1:8081/authenticate
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "verysecret"
}