apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
  labels:
    app: broker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      containers:
        - name: broker-service
          image: obededoreto/broker-service:1.0.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: AUTH_SERVICE_URL
              value: "http://authentication-service"
            - name: LOGGER_SERVICE_URL
              value: "http://logger-service"
            - name: MAIL_SERVICE_URL
              value: "http://mail-service"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbit:5672/
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  selector:
    app: broker-service
  ports:
    - protocol: TCP
      name: main-port
      port: 8080
      targetPort: 8080
  type: ClusterIP
