apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
  labels:
    app: mailer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      containers:
        - name: "mailer-service"
          image: obededoreto/mail-service:1.0.0
          env:
            - name: MAIL_DOMAIN
              value: "logs"
            - name: MAIL_HOST
              value: "mailhog"
            - name: MAIL_PORT
              value: "1025"
            - name: MAIL_ENCRYPTION
              value: "none"
            - name: MAIL_USERNAME
              value: ""
            - name: MAIL_PASSWORD
              value: ""
            - name: MAIL_FROM_NAME
              value: "Jhon Smith"
            - name: MAIL_FROM_ADDRESS
              value: "jhon.smith@example.com"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
    - protocol: TCP
      name: second-port
      port: 8083
      targetPort: 80
  type: ClusterIP
