services:
  caddy:
    image: obededoreto/micro-caddy:1.0.0
    restart: on-failure
    ports:
      - "8079:80"
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  authentication-service:
    image: obededoreto/authentication-service:1.0.0
    restart: on-failure
    environment:
      LOGGER_SERVICE_URL: "http://logger-service"
      DSN: "host=postgres port=5432 dbname=users user=postgres password=password sslmode=disable timezone=UTC connect_timeout=5"
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  broker-service:
    image: obededoreto/broker-service:1.0.0
    restart: on-failure
    environment:
      AUTH_SERVICE_URL: "http://authentication-service"
      LOGGER_SERVICE_URL: "http://logger-service"
      MAIL_SERVICE_URL: "http://mail-service"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: obededoreto/listener-service:1.0.0
    restart: on-failure
    environment:
      AUTH_SERVICE_URL: "http://authentication-service"
      LOGGER_SERVICE_URL: "http://logger-service"
      MAIL_SERVICE_URL: "http://mail-service"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8084:80"
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    image: obededoreto/logger-service:1.0.0
    restart: on-failure
    environment:
      MONGO_URL: "mongodb://mongo:27017"
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1

  front-end:
    image: obededoreto/front-end:1.0.2
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      BROKER_URL: "http://broker"
    deploy:
      mode: replicated
      replicas: 1

  mail-service:
    image: obededoreto/mail-service:1.0.0
    restart: on-failure
    environment:
      MAIL_DOMAIN: "localhost"
      MAIL_HOST: "mail-client"
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: "none"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROM_NAME: "Jhon Smith"
      MAIL_FROM_ADDRESS: "jhon.smith@example.com"
    ports:
      - "8083:80"
    deploy:
      mode: replicated
      replicas: 1

  # Third services
  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: global

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: dba@email.com
      PGADMIN_DEFAULT_PASSWORD: q1w2e3r4
    deploy:
      mode: global
    ports:
      - 8085:80

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    deploy:
      mode: global
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mongo:
    image: "mongo:4.2.17-bionic"
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db/

  mail-client:
    image: mailhog/mailhog:latest
    deploy:
      mode: global
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  caddy_data:
    external: true
  caddy_config:
